name: Install Dotnet Workflow
on: workflow_dispatch
jobs:
  install-dotnet-job:
    runs-on: ubuntu-latest
    steps:
      - name: install-dotnet-step
        run: |
          sudo apt-get update
          sudo apt-get install dotnet-sdk-9.0 -y
      - name: print-dotnet-version
        run: dotnet --version
