name: Sample Workflow
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print-greeting
        run: echo "Hello world"
      - name: pring-user
        run: whoami
      - name: print-os-version
        run: cat /etc/os-release
      
